const pokedex = [
    { number: 650, name: 'Chespin', type: 'Planta', description: 'El Pokémon Erizo Espinoso.' },
    { number: 651, name: 'Quilladin', type: 'Planta', description: 'El Pokémon Coraza Espinosa.' },
    { number: 652, name: 'Chesnaught', type: 'Planta/Lucha', description: 'El Pokémon Coraza Espinosa.' },
    { number: 653, name: 'Fennekin', type: 'Fuego', description: 'El Pokémon Zorro.' },
    { number: 654, name: 'Braixen', type: 'Fuego', description: 'El Pokémon Zorro.' },
    { number: 655, name: 'Delphox', type: 'Fuego/Psíquico', description: 'El Pokémon Zorro.' },
    { number: 656, name: 'Froakie', type: 'Agua', description: 'El Pokémon Rana Burbuja.' },
    { number: 657, name: 'Frogadier', type: 'Agua', description: 'El Pokémon Rana Burbuja.' },
    { number: 658, name: 'Greninja', type: 'Agua/Siniestro', description: 'El Pokémon Ninja.' },
    { number: 659, name: 'Bunnelby', type: 'Normal', description: 'El Pokémon Excavador.' },
    { number: 660, name: 'Diggersby', type: 'Normal/Tierra', description: 'El Pokémon Excavador.' },
    { number: 661, name: 'Fletchling', type: 'Normal/Volador', description: 'El Pokémon Petirrojo.' },
    { number: 662, name: 'Fletchinder', type: 'Fuego/Volador', description: 'El Pokémon Ascua.' },
    { number: 663, name: 'Talonflame', type: 'Fuego/Volador', description: 'El Pokémon Abrasador.' },
    { number: 664, name: 'Scatterbug', type: 'Bicho', description: 'El Pokémon Polvareda.' },
    { number: 665, name: 'Spewpa', type: 'Bicho', description: 'El Pokémon Polvareda.' },
    { number: 666, name: 'Vivillon', type: 'Bicho/Volador', description: 'El Pokémon Escama.' },
    { number: 667, name: 'Litleo', type: 'Fuego/Normal', description: 'El Pokémon Cachorro León.' },
    { number: 668, name: 'Pyroar', type: 'Fuego/Normal', description: 'El Pokémon Real.' },
    { number: 669, name: 'Flabébé', type: 'Hada', description: 'El Pokémon Una Flor.' },
    { number: 670, name: 'Floette', type: 'Hada', description: 'El Pokémon Una Flor.' },
    { number: 671, name: 'Florges', type: 'Hada', description: 'El Pokémon Jardín.' },
    { number: 672, name: 'Skiddo', type: 'Planta', description: 'El Pokémon Montura.' },
    { number: 673, name: 'Gogoat', type: 'Planta', description: 'El Pokémon Montura.' },
    { number: 674, name: 'Pancham', type: 'Lucha', description: 'El Pokémon Travieso.' },
    { number: 675, name: 'Pangoro', type: 'Lucha/Siniestro', description: 'El Pokémon Aterrador.' },
    { number: 676, name: 'Furfrou', type: 'Normal', description: 'El Pokémon Caniche.' },
    { number: 677, name: 'Espurr', type: 'Psíquico', description: 'El Pokémon Contención.' },
    { number: 678, name: 'Meowstic', type: 'Psíquico', description: 'El Pokémon Control.' },
    { number: 679, name: 'Honedge', type: 'Acero/Fantasma', description: 'El Pokémon Espada.' },
    { number: 680, name: 'Doublade', type: 'Acero/Fantasma', description: 'El Pokémon Espada.' },
    { number: 681, name: 'Aegislash', type: 'Acero/Fantasma', description: 'El Pokémon Espada Real.' },
    { number: 682, name: 'Spritzee', type: 'Hada', description: 'El Pokémon Perfume.' },
    { number: 683, name: 'Aromatisse', type: 'Hada', description: 'El Pokémon Fragancia.' },
    { number: 684, name: 'Swirlix', type: 'Hada', description: 'El Pokémon Algodón de Azúcar.' },
    { number: 685, name: 'Slurpuff', type: 'Hada', description: 'El Pokémon Merengue.' },
    { number: 686, name: 'Inkay', type: 'Siniestro/Psíquico', description: 'El Pokémon Rotación.' },
    { number: 687, name: 'Malamar', type: 'Siniestro/Psíquico', description: 'El Pokémon Reversión.' },
    { number: 688, name: 'Binacle', type: 'Roca/Agua', description: 'El Pokémon Dos Manos.' },
    { number: 689, name: 'Barbaracle', type: 'Roca/Agua', description: 'El Pokémon Colectivo.' },
    { number: 690, name: 'Skrelp', type: 'Veneno/Agua', description: 'El Pokémon Alga Camuflaje.' },
    { number: 691, name: 'Dragalge', type: 'Veneno/Dragón', description: 'El Pokémon Alga Camuflaje.' },
    { number: 692, name: 'Clauncher', type: 'Agua', description: 'El Pokémon Pistola de Agua.' },
    { number: 693, name: 'Clawitzer', type: 'Agua', description: 'El Pokémon Cañón.' },
    { number: 694, name: 'Helioptile', type: 'Eléctrico/Normal', description: 'El Pokémon Generador.' },
    { number: 695, name: 'Heliolisk', type: 'Eléctrico/Normal', description: 'El Pokémon Generador.' },
    { number: 696, name: 'Tyrunt', type: 'Roca/Dragón', description: 'El Pokémon Regio.' },
    { number: 697, name: 'Tyrantrum', type: 'Roca/Dragón', description: 'El Pokémon Déspota.' },
    { number: 698, name: 'Amaura', type: 'Roca/Hielo', description: 'El Pokémon Tundra.' },
    { number: 699, name: 'Aurorus', type: 'Roca/Hielo', description: 'El Pokémon Tundra.' },
    { number: 700, name: 'Sylveon', type: 'Hada', description: 'El Pokémon Vínculo.' },
    { number: 701, name: 'Hawlucha', type: 'Lucha/Volador', description: 'El Pokémon Llave Lucha.' },
    { number: 702, name: 'Dedenne', type: 'Eléctrico/Hada', description: 'El Pokémon Antena.' },
    { number: 703, name: 'Carbink', type: 'Roca/Hada', description: 'El Pokémon Gema.' },
    { number: 704, name: 'Goomy', type: 'Dragón', description: 'El Pokémon Tejido Blando.' },
    { number: 705, name: 'Sliggoo', type: 'Dragón', description: 'El Pokémon Tejido Blando.' },
    { number: 706, name: 'Goodra', type: 'Dragón', description: 'El Pokémon Dragón.' },
    { number: 707, name: 'Klefki', type: 'Acero/Hada', description: 'El Pokémon Llavero.' },
    { number: 708, name: 'Phantump', type: 'Fantasma/Planta', description: 'El Pokémon Tocon.' },
    { number: 709, name: 'Trevenant', type: 'Fantasma/Planta', description: 'El Pokémon Árbol Mayor.' },
    { number: 710, name: 'Pumpkaboo', type: 'Fantasma/Planta', description: 'El Pokémon Calabaza.' },
    { number: 711, name: 'Gourgeist', type: 'Fantasma/Planta', description: 'El Pokémon Calabaza.' },
    { number: 712, name: 'Bergmite', type: 'Hielo', description: 'El Pokémon Trozo de Hielo.' },
    { number: 713, name: 'Avalugg', type: 'Hielo', description: 'El Pokémon Iceberg.' },
    { number: 714, name: 'Noibat', type: 'Volador/Dragón', description: 'El Pokémon Onda de Sonido.' },
    { number: 715, name: 'Noivern', type: 'Volador/Dragón', description: 'El Pokémon Onda de Sonido.' },
    { number: 716, name: 'Xerneas', type: 'Hada', description: 'El Pokémon Vida.' },
    { number: 717, name: 'Yveltal', type: 'Siniestro/Volador', description: 'El Pokémon Destrucción.' },
    { number: 718, name: 'Zygarde', type: 'Dragón/Tierra', description: 'El Pokémon Orden.' },
    { number: 719, name: 'Diancie', type: 'Roca/Hada', description: 'El Pokémon Gema.' },
    { number: 720, name: 'Hoopa', type: 'Psíquico/Fantasma', description: 'El Pokémon Travesura.' },
    { number: 721, name: 'Volcanion', type: 'Fuego/Agua', description: 'El Pokémon Vapor.' }
];

module.exports = pokedex;